# Generated by Django 4.2.27 on 2026-01-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_material_threshold_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="equipment",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="material",
            name="model_number",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="material",
            name="shelf",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="material",
            name="warehouse",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
