# Generated by Django 4.2.27 on 2026-01-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_alter_material_equipment_alter_material_model_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="operator",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
    ]
