# Generated by Django 4.2.27 on 2026-01-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transaction_operator_transaction_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='equipment',
            new_name='usage',
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
